// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "../../components/sessionprovider";

export const metadata: Metadata = {
  title: "PLuz Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        {/* SessionProvider is a client component that wraps the whole app */}
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}